"""Playnite platform specification id -> logo name in the Batocera Carbon theme
(github.com/fabricecaruso/es-theme-carbon, art/logos/<name>.svg|png)."""
CARBON = {
    "3do": "3do", "adobe_flash": "flash", "amstrad_cpc": "amstradcpc", "apple_2": "apple2",
    "arcade": "arcade", "arduboy": None, "atari_2600": "atari2600", "atari_5200": "atari5200",
    "atari_7800": "atari7800", "atari_8bit": "atari8bit", "atari_falcon030": None,
    "atari_jaguar": "atarijaguar", "atari_lynx": "atarilynx", "atari_st": "atarist",
    "bandai_wonderswan_color": "wonderswancolor", "bandai_wonderswan": "wonderswan",
    "coleco_vision": "colecovision", "commodore_64": "c64", "commodore_amiga_cd32": "amigacd32",
    "commodore_amiga": "amiga", "commodore_cbm5x0": None, "commodore_cbm2": None,
    "commodore_pet": "pet", "commodore_plus4": "plus4", "commodore_vci20": "vic20",
    "fairchild_channelf": "channelf", "vectrex": "vectrex", "macintosh": "macintosh",
    "magnavox_odyssey_2": "odyssey2", "mattel_intellivision": "intellivision", "megaduck": "megaduck",
    "microsoft_msx": "msx1", "microsoft_msx2": "msx2", "xbox360": "xbox360", "xbox_one": None,
    "xbox_series": None, "xbox": "xbox", "nec_pc88": "pc88", "nec_pc98": "pc98", "nec_pcfx": "pcfx",
    "nec_supergrafx": "supergrafx", "nec_turbografx_16": "tg16", "nec_turbografx_cd": "tg-cd",
    "nintendo_3ds": "3ds", "nintendo_64": "n64", "nintendo_ds": "nds", "nintendo_dsi": "nds",
    "nintendo_nes": "nes", "nintendo_famicom_disk": "fds", "nintendo_gameandwatch": "gameandwatch",
    "nintendo_gameboyadvance": "gba", "nintendo_gameboycolor": "gbc", "nintendo_gameboy": "gb",
    "nintendo_gamecube": "gc", "nintendo_super_nes": "snes", "nintendo_switch": "switch",
    "nintendo_switch2": None, "nintendo_virtualboy": "virtualboy", "nintendo_wiiu": "wiiu",
    "nintendo_wii": "wii", "pc_dos": "pc", "pc_linux": "linux", "pc_windows": "windows",
    "sega_32x": "sega32x", "sega_cd": "segacd", "sega_dreamcast": "dreamcast",
    "sega_gamegear": "gamegear", "sega_genesis": "genesis", "sega_mastersystem": "mastersystem",
    "sega_saturn": "saturn", "sega_sg1000": "sg-1000", "sharp_x1": "x1", "sharp_x68000": "x68000",
    "sinclair_zxspectrum3": "zxspectrum", "sinclair_zxspectrum": "zxspectrum", "sinclair_zx81": "zx81",
    "snk_neogeo_aes": "neogeo", "snk_neogeo_cd": "neogeocd", "snk_neogeopocket_color": "ngpc",
    "snk_neogeopocket": "ngp", "sony_playstation2": "ps2", "sony_playstation3": "ps3",
    "sony_playstation4": "ps4", "sony_playstation5": None, "sony_psp": "psp", "sony_vita": "psvita",
    "sony_playstation": "psx", "ti_83": None, "thomson_mo5": "thomson", "thomson_to7": "thomson",
    "tic_80": "tic80", "uzebox": "uzebox", "wasm4": "wasm4", "watara_supervision": "supervision",
    "philips_cdi": "cdi", "pokemon_mini": "pokemini",
}
